const fs = require('fs');
const path = require('path');

const envPath = path.resolve(__dirname, '../.env');
const outputPath = path.resolve(__dirname, '../src/api/envConfig.ts');

let apiMode = 'mock';
let apiUrl = 'http://10.0.2.2:5000/api';

if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf-8');
  const lines = envContent.split(/\r?\n/);
  for (const line of lines) {
    const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
    if (match) {
      const key = match[1];
      let value = match[2] || '';
      // Remove surrounding quotes if any
      if (value.startsWith('"') && value.endsWith('"')) {
        value = value.slice(1, -1);
      } else if (value.startsWith("'") && value.endsWith("'")) {
        value = value.slice(1, -1);
      }
      if (key === 'API_MODE') apiMode = value;
      if (key === 'API_URL') apiUrl = value;
    }
  }
}

const configContent = `// Auto-generated by load-env.js. Do not edit directly.
export const API_MODE = '${apiMode}';
export const API_URL = '${apiUrl}';
`;

// Ensure directory exists
const dir = path.dirname(outputPath);
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync(outputPath, configContent, 'utf-8');
console.log(`Successfully generated envConfig.ts: mode=${apiMode}, url=${apiUrl}`);
